version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: karolbolsas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: karolbolsas_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata2:
